# Read data

In [2]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [3]:
befor_preprocess = pd.read_excel("Before_Pre_Processing.xlsx", sheet_name="Feuil1")
print("S1Q06_P1" in befor_preprocess.columns)
befor_preprocess

True

,USER,S1Q01,S1Q02,S1Q04,S1Q05,S1Q061,S1Q06_P1,S1Q062,S1Q063,S1Q065,...,S5Q05_b13,S5Q05_b14,S5Q05_b15,S5Q05_b16,S5Q05_b17,S5Q05_b18,S5Q05_b19,S5Q05_b20,S5Q05_b21,S5Q05_b22
0,P100131,1,4,3,0.0,1,0.80,2,2,2,...,1,1,1,4,5,3,4,5,2,3
1,P100849,1,5,6,0.0,1,10.00,2,2,1,...,3,3,5,5,3,3,4,4,4,3
2,P102621,1,5,3,0.0,1,10.00,2,2,2,...,5,3,4,3,3,3,4,3,3,1
3,P103321,1,1,4,0.0,1,2.00,1,2,2,...,5,5,5,3,3,4,3,1,1,3
4,P104491,1,1,2,0.0,1,40.00,2,1,1,...,4,4,4,3,4,3,4,3,3,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,P119630,3,3,6,0.0,3,-20.00,3,3,2,...,4,4,4,4,3,3,4,3,4,2
266,P119725,3,2,6,0.0,3,-10.00,2,2,3,...,5,5,5,4,3,2,2,2,2,1
267,P119802,6,2,3,0.0,3,-20.00,3,2,2,...,2,3,2,1,1,1,1,1,1,1
268,P120012,5,4,6,0.0,3,-16.45,3,2,1,...,4,5,5,5,4,4,5,5,5,3
269,P120027,4,5,6,0.0,3,-92.00,2,3,3,...,4,4,4,5,5,5,4,4,3,3

In [4]:
after_preprocess = pd.read_excel("After_Pre_Processing.xlsx", sheet_name="Feuil1")
after_preprocess

,USER,S1Q01nor,S1Q05,S1Q061nor,S1Q06_P1nor,S1Q062nor,S1Q063NOR,S1Q065NOR,S1Q067NOR,S1Q071nor,...,S5Q05_b13,S5Q05_b14,S5Q05_b15,S5Q05_b16,S5Q05_b17,S5Q05_b18,S5Q05_b19,S5Q05_b20,S5Q05_b21,S5Q05_b22
0,P100017,0.0,1,1.0,0.453125,1.0,1.0,1.0,1.0,0.005732,...,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
1,P100131,0.0,0,0.0,0.483333,0.5,0.5,0.5,0.0,0.006369,...,0.00,0.00,0.00,0.75,1.00,0.50,0.75,1.00,0.25,0.50
2,P100137,0.0,1,0.5,0.479167,0.5,0.5,0.5,0.5,0.001274,...,0.25,0.50,0.25,0.50,0.75,0.25,0.25,0.75,0.00,0.25
3,P100169,0.1,1,1.0,0.427083,1.0,1.0,1.0,1.0,0.000637,...,0.50,0.50,0.50,0.25,0.50,0.50,0.25,0.25,0.25,0.00
4,P100309,0.0,0,0.5,0.479167,0.5,0.5,0.5,0.5,0.001274,...,0.50,1.00,1.00,0.50,1.00,1.00,0.00,1.00,1.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,P120241,0.5,1,0.0,0.479687,0.5,0.5,0.0,0.5,0.000637,...,1.00,1.00,0.75,1.00,1.00,1.00,1.00,1.00,1.00,0.50
266,P120268,0.5,0,0.0,0.583333,0.0,0.5,0.5,1.0,0.000000,...,0.50,0.25,0.25,0.75,0.25,0.50,0.75,0.50,0.50,0.50
267,P120287,0.5,0,0.0,1.000000,0.0,0.0,0.0,0.5,0.000318,...,1.00,1.00,1.00,0.75,0.75,0.75,0.75,0.75,0.75,0.75
268,P120338,0.5,0,0.5,0.479167,0.5,0.5,0.5,0.5,0.000318,...,0.50,0.75,0.50,0.75,0.50,0.50,1.00,0.25,0.00,0.00
269,P120360,0.4,0,0.5,0.479167,0.5,0.5,0.5,0.5,0.000955,...,1.00,1.00,1.00,1.00,0.75,0.50,0.00,1.00,1.00,0.00

- Before-Pre-Processing (b), in which S1Q061 and S1Q06P1 are NOT pre-processed;
- After-Pre-Processing (anotp), in which S1Q061 and S1Q06P1 are NOT PRE-PROCESSED;
- After-Pre-Processing (ap), in which S1Q061 and S1Q06P1 are PRE-PROCESSED.

Please perform experiments over 30 different partitions of training-test sets. Please provide a table with
the following statistics of the performance metrics discussed during the lecture: min, max, avg, stddev.

In [5]:
import numpy as np
from sklearn.metrics import (
    f1_score,
    precision_score,
    recall_score,
    r2_score,
    mean_absolute_error,
    mean_squared_error,
    accuracy_score,
)
from sklearn.model_selection import KFold
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor

# Full Dataset

## Before-Pre-Processing (b)
### For S1Q061 Column

In [8]:
if "USER" in befor_preprocess.columns:
    befor_preprocess.drop(columns=["USER"], inplace=True)

In [9]:
befor_preprocess["S1Q061"].unique(), befor_preprocess["S1Q061"].dtype

(array([1, 2, 3]), dtype('int64'))

In [45]:
from typing import Callable


def make_results(n_splits:int, x_data: pd.DataFrame, y_data: pd.DataFrame, base_model: Callable, metrics: list):

    raw_results = {
        mtric.__name__.rsplit("_", 1)[0]: [] for mtric in metrics
    }
    for train_index, test_index in KFold(n_splits=n_splits).split(befor_preprocess):
        x_train, x_test = x_data.iloc[train_index], x_data.iloc[test_index]
        y_train, y_test = y_data.iloc[train_index], y_data.iloc[test_index]
        model = base_model()
        model.fit(x_train, y_train)
        y_pred = model.predict(x_test)
        for metric in metrics:
            try:
                m = metric(y_test, y_pred, average="weighted")
            except TypeError:
                m = metric(y_test, y_pred)
            raw_results[metric.__name__.rsplit("_", 1)[0]].append(m)
    final_results = {}
    for metric in metrics:
        metric_name = metric.__name__.rsplit("_", 1)[0]
        final_results[metric_name] = {
            "min": min(raw_results[metric_name]),
            "max": max(raw_results[metric_name]),
            "mean": np.mean(raw_results[metric_name]),
            "stddev": np.std(raw_results[metric_name]),
        }
    return final_results

In [46]:
def accuracy_score_(y_true, y_pred, average):
    return accuracy_score(y_true, y_pred)

In [47]:
regression_metrics = [r2_score, mean_squared_error, mean_absolute_error]
classification_metrics = [f1_score, precision_score, recall_score, accuracy_score]

In [48]:
x_data = befor_preprocess.drop(columns=["S1Q061"])
y_data = befor_preprocess["S1Q061"]
dataset_b_results_s1q061 = make_results(n_splits=30,
                                 x_data=x_data,
                                 y_data=y_data,
                                 base_model=DecisionTreeClassifier,
                                 metrics=classification_metrics)
dataset_b_results_s1q061

{'f1': {'min': 0.8888888888888888,
  'max': 1.0,
  'mean': 0.9943355119825709,
  'stddev': 0.022243571273377293},
 'precision': {'min': 0.911111111111111,
  'max': 1.0,
  'mean': 0.997037037037037,
  'stddev': 0.015956043872991144},
 'recall': {'min': 0.8888888888888888,
  'max': 1.0,
  'mean': 0.9925925925925926,
  'stddev': 0.027715980642769946},
 'accuracy': {'min': 0.8888888888888888,
  'max': 1.0,
  'mean': 0.9925925925925926,
  'stddev': 0.027715980642769946}}

### For S1Q06_P1 Column

In [49]:
befor_preprocess["S1Q06_P1"].unique(), befor_preprocess["S1Q06_P1"].dtype

(array([  0.8 ,  10.  ,   2.  ,  40.  ,  20.  ,   3.  ,  30.  ,   7.  ,
          5.  ,  11.  ,  15.  ,  32.  ,  17.  , 100.  ,   0.1 ,   0.  ,
         -5.  , -10.  , -40.  , -25.  , -30.  ,  -4.  , -20.  , -45.  ,
         -1.1 , -15.  ,  -6.5 , -18.  , -16.45, -92.  ]),
 dtype('float64'))

Since this column is continuous, we can use the Decision Tree Regressor to predict the values.

In [50]:
x_data = befor_preprocess.drop(columns=["S1Q06_P1"])
y_data = befor_preprocess["S1Q06_P1"]
dataset_b_results_s1q06p1 = make_results(n_splits=30,
                                 x_data=x_data,
                                 y_data=y_data,
                                 base_model=DecisionTreeRegressor,
                                 metrics=regression_metrics)
dataset_b_results_s1q06p1

{'r2': {'min': -33.3858695652174,
  'max': 1.0,
  'mean': -1.6700612791617817,
  'stddev': 6.994181578063063},
 'mean_squared': {'min': 0.0,
  'max': 1796.5555555555557,
  'mean': 200.51065740740742,
  'stddev': 405.37084921884406},
 'mean_absolute': {'min': 0.0,
  'max': 27.0,
  'mean': 5.631296296296297,
  'stddev': 7.745453662300372}}

## After-Pre-Processing (anotp)
After-Pre-Processing (anotp), in which S1Q061 and S1Q06P1 are NOT PRE-PROCESSED

In [51]:
if "USER" in after_preprocess.columns:
    after_preprocess.drop(columns=["USER"], inplace=True)
anotp_df = after_preprocess.copy()
anotp_df[['S1Q061', 'S1Q06_P1']] = befor_preprocess[['S1Q061', 'S1Q06_P1']]


### For S1Q061 Column

In [52]:
x_data = anotp_df.drop(columns=["S1Q061"])
y_data = anotp_df["S1Q061"]
dataset_anotp_results_s1q061 = make_results(n_splits=30,
                                 x_data=x_data,
                                 y_data=y_data,
                                 base_model=DecisionTreeClassifier,
                                 metrics=classification_metrics)
dataset_anotp_results_s1q061

{'f1': {'min': 0.8888888888888888,
  'max': 1.0,
  'mean': 0.9943355119825709,
  'stddev': 0.022243571273377293},
 'precision': {'min': 0.911111111111111,
  'max': 1.0,
  'mean': 0.997037037037037,
  'stddev': 0.015956043872991144},
 'recall': {'min': 0.8888888888888888,
  'max': 1.0,
  'mean': 0.9925925925925926,
  'stddev': 0.027715980642769946},
 'accuracy': {'min': 0.8888888888888888,
  'max': 1.0,
  'mean': 0.9925925925925926,
  'stddev': 0.027715980642769946}}

### For S1Q06_P1 Column

In [53]:
x_data = anotp_df.drop(columns=["S1Q06_P1"])
y_data = anotp_df["S1Q06_P1"]
dataset_anotp_results_s1q06p1 = make_results(n_splits=30,
                                 x_data=x_data,
                                 y_data=y_data,
                                 base_model=DecisionTreeRegressor,
                                 metrics=regression_metrics)
dataset_anotp_results_s1q06p1

{'r2': {'min': -54.12499999999999,
  'max': 1.0,
  'mean': -4.199885384151107,
  'stddev': 12.698596916464789},
 'mean_squared': {'min': 0.0,
  'max': 1163.5577777777778,
  'mean': 267.4050277777778,
  'stddev': 396.62678181380676},
 'mean_absolute': {'min': 0.0,
  'max': 24.422222222222224,
  'mean': 6.106111111111111,
  'stddev': 7.915636755619448}}

## After-Pre-Processing (ap)
After-Pre-Processing (ap), in which S1Q061 and S1Q06P1 are PRE-PROCESSED

### For S1Q061 Column

In [58]:
after_preprocess_ = after_preprocess.copy()
unique_vals = sorted(after_preprocess_["S1Q061nor"].unique())
mapper = dict(zip(unique_vals, range(len(unique_vals))))
after_preprocess_["S1Q061nor"] = after_preprocess_["S1Q061nor"].map(mapper)
after_preprocess_["S1Q061nor"].unique(), after_preprocess_["S1Q061nor"].dtype

(array([2, 0, 1]), dtype('int64'))

In [59]:
x_data = after_preprocess_.drop(columns=["S1Q061nor"])
y_data = after_preprocess_["S1Q061nor"]
dataset_ap_results_s1q061 = make_results(n_splits=30,
                                 x_data=x_data,
                                 y_data=y_data,
                                 base_model=DecisionTreeClassifier,
                                 metrics=classification_metrics)
dataset_ap_results_s1q061

{'f1': {'min': 0.8839506172839506,
  'max': 1.0,
  'mean': 0.9924279835390947,
  'stddev': 0.028339063288798108},
 'precision': {'min': 0.911111111111111,
  'max': 1.0,
  'mean': 0.9940740740740741,
  'stddev': 0.02217278451421598},
 'recall': {'min': 0.8888888888888888,
  'max': 1.0,
  'mean': 0.9925925925925926,
  'stddev': 0.027715980642769946},
 'accuracy': {'min': 0.8888888888888888,
  'max': 1.0,
  'mean': 0.9925925925925926,
  'stddev': 0.027715980642769946}}

### For S1Q06_P1 Column

In [60]:

after_preprocess["S1Q06_P1nor"].unique(), after_preprocess["S1Q06_P1nor"].dtype

(array([0.453125  , 0.48333333, 0.47916667, 0.42708333, 0.27083333,
        0.53125   , 0.48958333, 0.6875    , 0.34895833, 0.32291667,
        0.45833333, 0.375     , 0.58333333, 0.49479167, 0.24479167,
        0.4734375 , 0.63541667, 0.515625  , 0.50520833, 0.40104167,
        0.4453125 , 0.53645833, 0.55729167, 0.38541667, 0.64583333,
        0.56770833, 0.39348958, 0.        , 1.        , 0.4796875 ]),
 dtype('float64'))

In [61]:
x_data = after_preprocess.drop(columns=["S1Q06_P1nor"])
y_data = after_preprocess["S1Q06_P1nor"]
dataset_ap_results_s1q06p1 = make_results(n_splits=30,
                                 x_data=x_data,
                                 y_data=y_data,
                                 base_model=DecisionTreeRegressor,
                                 metrics=regression_metrics)
dataset_ap_results_s1q06p1

{'r2': {'min': -48.590179362267435,
  'max': 1.0,
  'mean': -2.427233291329696,
  'stddev': 9.476755020038619},
 'mean_squared': {'min': 2.3967128196818935e-33,
  'max': 0.024000048225308643,
  'mean': 0.005254546742380402,
  'stddev': 0.007138363938378175},
 'mean_absolute': {'min': 4.3175339846533866e-17,
  'max': 0.07986111111111112,
  'mean': 0.0275385802469136,
  'stddev': 0.019770060557676807}}

# INVBOOL
Then please produce two more sets of experiments, by using the following variables in the predictor set:
the first is referred to as INVBOOL
- S2Q01-a-201801-19
- S1Q05
- S5Q05-a01 to S5Q05-b22
- S4Q011AL

## Before-Pre-Processing (b)

### For S1Q061 Column

In [62]:
print(*befor_preprocess.columns, sep="\n")

S1Q01
S1Q02
S1Q04
S1Q05
S1Q061
S1Q06_P1
S1Q062
S1Q063
S1Q065
S1Q067
S1Q071
S1Q072
S1Q081
S1Q082
S1Q09_b
S2Q01_a_201501
S2Q01_a_201801
S2Q01_a_201502
S2Q01_a_201802
S2Q01_a_201503
S2Q01_a_201803
S2Q01_a_201504
S2Q01_a_201804
S2Q01_a_201505
S2Q01_a_201805
S2Q01_a_201506
S2Q01_a_201806
S2Q01_a_201507
S2Q01_a_201807
S2Q01_a_201508
S2Q01_a_201808
S2Q01_a_201509
S2Q01_a_201809
S2Q01_a_201510
S2Q01_a_201810
S2Q01_b_201511
S2Q01_b_201811
S2Q01_b_201512
S2Q01_b_201812
S2Q01_b_201513
S2Q01_b_201813
S2Q01_b_201514
S2Q01_b_201814
S2Q01_b_201515
S2Q01_b_201815
S2Q01_b_201516
S2Q01_b_201816
S2Q01_b_201517
S2Q01_b_201817
S2Q01_b_201518
S2Q01_b_201818
S2Q01_b_201519
S2Q01_b_201819
S2Q02_01
S2Q02_02
S2Q02_03
S2Q02_04
S2Q02_05
S2Q02_06
S2Q02_07
S2Q02_08
S2Q02_09
S2Q02_10
S2Q02_11
S3Q01_20151
S3Q01_20181
S3Q01_20152
S3Q01_20182
S3Q02_01
S3Q02_02
S3Q02_03
S3Q02_04
S3Q02_05
S3Q02_06
S3Q02_07
S3Q02_08
S3Q02_09
S3Q02_10
S3Q03-AL
S4Q01
S4Q011_AL
S4Q021
S4Q022
S4Q023
S4Q024
S4Q025
S4Q026
S4Q031
S4Q041
S4Q051
S4Q061
S4Q071
S5Q010-AL
S5Q02
S5Q03
S5Q04
S5Q05_a01
S5Q05_a02
S5Q05_a03
S5Q05_a04
S5Q05_a05
S5Q05_a06
S5Q05_a24
S5Q05_a07
S5Q05_a08
S5Q05_a09
S5Q05_a10
S5Q05_a11
S5Q05_a12
S5Q05_b13
S5Q05_b14
S5Q05_b15
S5Q05_b16
S5Q05_b17
S5Q05_b18
S5Q05_b19
S5Q05_b20
S5Q05_b21
S5Q05_b22

In [63]:
import re


invbool_cols = ["S2Q01_a_201801", "S1Q05", "S4Q011_AL"]
for col in befor_preprocess.columns:
    if re.match(r"S5Q05_[ab]\d\d", col):
        invbool_cols.append(col)
invbool_cols

['S2Q01_a_201801',
 'S1Q05',
 'S4Q011_AL',
 'S5Q05_a01',
 'S5Q05_a02',
 'S5Q05_a03',
 'S5Q05_a04',
 'S5Q05_a05',
 'S5Q05_a06',
 'S5Q05_a24',
 'S5Q05_a07',
 'S5Q05_a08',
 'S5Q05_a09',
 'S5Q05_a10',
 'S5Q05_a11',
 'S5Q05_a12',
 'S5Q05_b13',
 'S5Q05_b14',
 'S5Q05_b15',
 'S5Q05_b16',
 'S5Q05_b17',
 'S5Q05_b18',
 'S5Q05_b19',
 'S5Q05_b20',
 'S5Q05_b21',
 'S5Q05_b22']

In [64]:
x_data = befor_preprocess[invbool_cols]
y_data = befor_preprocess["S1Q061"]
invbool_b_results_s1q061 = make_results(n_splits=30,
                                 x_data=x_data,
                                 y_data=y_data,
                                 base_model=DecisionTreeClassifier,
                                 metrics=classification_metrics)
invbool_b_results_s1q061

{'f1': {'min': 0.0,
  'max': 0.9411764705882353,
  'mean': 0.5823204301145478,
  'stddev': 0.2421768047264033},
 'precision': {'min': 0.0,
  'max': 1.0,
  'mean': 0.9216931216931218,
  'stddev': 0.2506708336784136},
 'recall': {'min': 0.0,
  'max': 0.8888888888888888,
  'mean': 0.4555555555555555,
  'stddev': 0.23544022333796769},
 'accuracy': {'min': 0.0,
  'max': 0.8888888888888888,
  'mean': 0.4555555555555555,
  'stddev': 0.23544022333796769}}

### For S1Q06_P1 Column

In [65]:
x_data = befor_preprocess[invbool_cols]
y_data = befor_preprocess["S1Q06_P1"]
invbool_b_results_s1q06p1 = make_results(n_splits=30,
                                 x_data=x_data,
                                 y_data=y_data,
                                 base_model=DecisionTreeRegressor,
                                 metrics=regression_metrics)
invbool_b_results_s1q06p1

{'r2': {'min': -51.72822468373585,
  'max': 0.0,
  'mean': -3.8653916361313594,
  'stddev': 9.635073816197357},
 'mean_squared': {'min': 27.77777777777778,
  'max': 1944.2233333333336,
  'mean': 594.9826851851852,
  'stddev': 578.3076005389413},
 'mean_absolute': {'min': 3.3333333333333335,
  'max': 31.555555555555557,
  'mean': 14.0162962962963,
  'stddev': 7.788772114797134}}

## After-Pre-Processing (anotp)

### For S1Q061 Column

In [66]:
x_data = anotp_df[invbool_cols]
y_data = anotp_df["S1Q061"]
invbool_anotp_results_s1q061 = make_results(n_splits=30,
                                 x_data=x_data,
                                 y_data=y_data,
                                 base_model=DecisionTreeClassifier,
                                 metrics=classification_metrics)
invbool_anotp_results_s1q061

{'f1': {'min': 0.0,
  'max': 0.9411764705882353,
  'mean': 0.5618640346581523,
  'stddev': 0.24729228125760544},
 'precision': {'min': 0.0,
  'max': 1.0,
  'mean': 0.9524074074074075,
  'stddev': 0.18660759279832717},
 'recall': {'min': 0.0,
  'max': 0.8888888888888888,
  'mean': 0.437037037037037,
  'stddev': 0.24162231748592725},
 'accuracy': {'min': 0.0,
  'max': 0.8888888888888888,
  'mean': 0.437037037037037,
  'stddev': 0.24162231748592725}}

### For S1Q06_P1 Column

In [67]:
x_data = anotp_df[invbool_cols]
y_data = anotp_df["S1Q06_P1"]
invbool_anotp_results_s1q06p1 = make_results(n_splits=30,
                                 x_data=x_data,
                                 y_data=y_data,
                                 base_model=DecisionTreeRegressor,
                                 metrics=regression_metrics)
invbool_anotp_results_s1q06p1

{'r2': {'min': -105.46999999999998,
  'max': 0.0,
  'mean': -7.582676275142402,
  'stddev': 20.611538086891105},
 'mean_squared': {'min': 35.138888888888886,
  'max': 2211.1122222222225,
  'mean': 632.1031574074075,
  'stddev': 619.853783277615},
 'mean_absolute': {'min': 3.1666666666666665,
  'max': 31.666666666666668,
  'mean': 15.06611111111111,
  'stddev': 8.850178016623504}}

## After-Pre-Processing (ap)

### For S1Q061 Column

In [68]:
after_preprocess_["S1Q061nor"].unique(), after_preprocess_["S1Q061nor"].dtype

(array([2, 0, 1]), dtype('int64'))

In [69]:
x_data = after_preprocess_[invbool_cols]
y_data = after_preprocess_["S1Q061nor"]
invbool_ap_results_s1q061 = make_results(n_splits=30,
                                 x_data=x_data,
                                 y_data=y_data,
                                 base_model=DecisionTreeClassifier,
                                 metrics=classification_metrics)
invbool_ap_results_s1q061

{'f1': {'min': 0.16666666666666666,
  'max': 0.8828282828282829,
  'mean': 0.4643677207566096,
  'stddev': 0.18102799202209582},
 'precision': {'min': 0.16666666666666666,
  'max': 1.0,
  'mean': 0.5361302175191065,
  'stddev': 0.2234884431092952},
 'recall': {'min': 0.1111111111111111,
  'max': 0.8888888888888888,
  'mean': 0.4592592592592592,
  'stddev': 0.19401186449938956},
 'accuracy': {'min': 0.1111111111111111,
  'max': 0.8888888888888888,
  'mean': 0.4592592592592592,
  'stddev': 0.19401186449938956}}

### For S1Q06_P1 Column

In [70]:
x_data = after_preprocess_[invbool_cols]
y_data = after_preprocess_["S1Q06_P1nor"]
invbool_ap_results_s1q06p1 = make_results(n_splits=30,
                                 x_data=x_data,
                                 y_data=y_data,
                                 base_model=DecisionTreeRegressor,
                                 metrics=regression_metrics)
invbool_ap_results_s1q06p1

{'r2': {'min': -75.32000000000001,
  'max': 0.007838043478261225,
  'mean': -7.718837194952721,
  'stddev': 14.411394925187016},
 'mean_squared': {'min': 0.0018838011188271624,
  'max': 0.05252040533371913,
  'mean': 0.018866989826469265,
  'stddev': 0.01535918309198645},
 'mean_absolute': {'min': 0.02488425925925926,
  'max': 0.16498842592592594,
  'mean': 0.08109857253086418,
  'stddev': 0.03868189614636144}}

# INVCONT
the second is referred to as INVCONT
- S2Q01-a-201801-19
- S1Q05
- S5Q05-a01 - S5Q05-b22
- S4Q021 to S4Q026

In [71]:
print(*befor_preprocess.columns, sep="\n")

S1Q01
S1Q02
S1Q04
S1Q05
S1Q061
S1Q06_P1
S1Q062
S1Q063
S1Q065
S1Q067
S1Q071
S1Q072
S1Q081
S1Q082
S1Q09_b
S2Q01_a_201501
S2Q01_a_201801
S2Q01_a_201502
S2Q01_a_201802
S2Q01_a_201503
S2Q01_a_201803
S2Q01_a_201504
S2Q01_a_201804
S2Q01_a_201505
S2Q01_a_201805
S2Q01_a_201506
S2Q01_a_201806
S2Q01_a_201507
S2Q01_a_201807
S2Q01_a_201508
S2Q01_a_201808
S2Q01_a_201509
S2Q01_a_201809
S2Q01_a_201510
S2Q01_a_201810
S2Q01_b_201511
S2Q01_b_201811
S2Q01_b_201512
S2Q01_b_201812
S2Q01_b_201513
S2Q01_b_201813
S2Q01_b_201514
S2Q01_b_201814
S2Q01_b_201515
S2Q01_b_201815
S2Q01_b_201516
S2Q01_b_201816
S2Q01_b_201517
S2Q01_b_201817
S2Q01_b_201518
S2Q01_b_201818
S2Q01_b_201519
S2Q01_b_201819
S2Q02_01
S2Q02_02
S2Q02_03
S2Q02_04
S2Q02_05
S2Q02_06
S2Q02_07
S2Q02_08
S2Q02_09
S2Q02_10
S2Q02_11
S3Q01_20151
S3Q01_20181
S3Q01_20152
S3Q01_20182
S3Q02_01
S3Q02_02
S3Q02_03
S3Q02_04
S3Q02_05
S3Q02_06
S3Q02_07
S3Q02_08
S3Q02_09
S3Q02_10
S3Q03-AL
S4Q01
S4Q011_AL
S4Q021
S4Q022
S4Q023
S4Q024
S4Q025
S4Q026
S4Q031
S4Q041
S4Q051
S4Q061
S4Q071
S5Q010-AL
S5Q02
S5Q03
S5Q04
S5Q05_a01
S5Q05_a02
S5Q05_a03
S5Q05_a04
S5Q05_a05
S5Q05_a06
S5Q05_a24
S5Q05_a07
S5Q05_a08
S5Q05_a09
S5Q05_a10
S5Q05_a11
S5Q05_a12
S5Q05_b13
S5Q05_b14
S5Q05_b15
S5Q05_b16
S5Q05_b17
S5Q05_b18
S5Q05_b19
S5Q05_b20
S5Q05_b21
S5Q05_b22

In [72]:
invcot_cols = ["S2Q01_a_201801", "S1Q05"]
for col in befor_preprocess.columns:
    if re.match(r"S5Q05_[ab]\d\d", col) or re.match(r"S4Q02[123456]", col):
        invcot_cols.append(col)
for col in invcot_cols:
    assert col in befor_preprocess.columns, f"{col} not in {befor_preprocess.columns}"
invcot_cols

['S2Q01_a_201801',
 'S1Q05',
 'S4Q021',
 'S4Q022',
 'S4Q023',
 'S4Q024',
 'S4Q025',
 'S4Q026',
 'S5Q05_a01',
 'S5Q05_a02',
 'S5Q05_a03',
 'S5Q05_a04',
 'S5Q05_a05',
 'S5Q05_a06',
 'S5Q05_a24',
 'S5Q05_a07',
 'S5Q05_a08',
 'S5Q05_a09',
 'S5Q05_a10',
 'S5Q05_a11',
 'S5Q05_a12',
 'S5Q05_b13',
 'S5Q05_b14',
 'S5Q05_b15',
 'S5Q05_b16',
 'S5Q05_b17',
 'S5Q05_b18',
 'S5Q05_b19',
 'S5Q05_b20',
 'S5Q05_b21',
 'S5Q05_b22']

## Before-Pre-Processing (b)
### For S1Q061 Column

In [73]:
x_data = befor_preprocess[invcot_cols]
y_data = befor_preprocess["S1Q061"]
invcot_b_results_s1q061 = make_results(n_splits=30,
                                 x_data=x_data,
                                 y_data=y_data,
                                 base_model=DecisionTreeClassifier,
                                 metrics=classification_metrics)
invcot_b_results_s1q061

{'f1': {'min': 0.0,
  'max': 0.9411764705882353,
  'mean': 0.5761378146182068,
  'stddev': 0.2693693770529615},
 'precision': {'min': 0.0,
  'max': 1.0,
  'mean': 0.9187654320987655,
  'stddev': 0.25171734486127195},
 'recall': {'min': 0.0,
  'max': 0.8888888888888888,
  'mean': 0.45925925925925914,
  'stddev': 0.2577735206119306},
 'accuracy': {'min': 0.0,
  'max': 0.8888888888888888,
  'mean': 0.45925925925925914,
  'stddev': 0.2577735206119306}}

### For S1Q06_P1 Column

In [74]:
x_data = befor_preprocess[invcot_cols]
y_data = befor_preprocess["S1Q06_P1"]
invcot_b_results_s1q06p1 = make_results(n_splits=30,
                                 x_data=x_data,
                                 y_data=y_data,
                                 base_model=DecisionTreeRegressor,
                                 metrics=regression_metrics)
invcot_b_results_s1q06p1

{'r2': {'min': -475.50499999999994,
  'max': 0.0,
  'mean': -19.17823404535546,
  'stddev': 85.26108858425891},
 'mean_squared': {'min': 2.7777777777777777,
  'max': 2451.695555555556,
  'mean': 549.5223148148149,
  'stddev': 599.8993782727342},
 'mean_absolute': {'min': 0.5555555555555556,
  'max': 33.22222222222222,
  'mean': 14.293703703703704,
  'stddev': 8.945307266105955}}

## After-Pre-Processing (anotp)
### For S1Q061 Column

In [75]:
x_data = anotp_df[invcot_cols]
y_data = anotp_df["S1Q061"]
invcot_anotp_results_s1q061 = make_results(n_splits=30,
                                 x_data=x_data,
                                 y_data=y_data,
                                 base_model=DecisionTreeClassifier,
                                 metrics=classification_metrics)
invcot_anotp_results_s1q061

{'f1': {'min': 0.2,
  'max': 0.9411764705882353,
  'mean': 0.6087047538518127,
  'stddev': 0.19726144711053442},
 'precision': {'min': 0.5925925925925926,
  'max': 1.0,
  'mean': 0.983641975308642,
  'stddev': 0.07413898904552567},
 'recall': {'min': 0.1111111111111111,
  'max': 0.8888888888888888,
  'mean': 0.4740740740740741,
  'stddev': 0.19654072831735703},
 'accuracy': {'min': 0.1111111111111111,
  'max': 0.8888888888888888,
  'mean': 0.4740740740740741,
  'stddev': 0.19654072831735703}}

### For S1Q06_P1 Column

In [76]:
x_data = anotp_df[invcot_cols]
y_data = anotp_df["S1Q06_P1"]
invcot_anotp_results_s1q06p1 = make_results(n_splits=30,
                                 x_data=x_data,
                                 y_data=y_data,
                                 base_model=DecisionTreeRegressor,
                                 metrics=regression_metrics)
invcot_anotp_results_s1q06p1

{'r2': {'min': -58.577319587628864,
  'max': 0.05179611305099763,
  'mean': -5.581691601645054,
  'stddev': 12.308973509474791},
 'mean_squared': {'min': 61.111111111111114,
  'max': 4016.6666666666665,
  'mean': 703.9692222222222,
  'stddev': 844.4743754731236},
 'mean_absolute': {'min': 4.138888888888889,
  'max': 47.77777777777778,
  'mean': 16.21037037037037,
  'stddev': 10.246177821272202}}

## After-Pre-Processing (ap)
### For S1Q061 Column

In [77]:
x_data = after_preprocess_[invcot_cols]
y_data = after_preprocess_["S1Q061nor"]
invcot_ap_results_s1q061 = make_results(n_splits=30,
                                 x_data=x_data,
                                 y_data=y_data,
                                 base_model=DecisionTreeClassifier,
                                 metrics=classification_metrics)
invcot_ap_results_s1q061

{'f1': {'min': 0.17777777777777778,
  'max': 0.792022792022792,
  'mean': 0.5030588547255214,
  'stddev': 0.16522201908853018},
 'precision': {'min': 0.14814814814814814,
  'max': 1.0,
  'mean': 0.5421869488536155,
  'stddev': 0.2181102485848563},
 'recall': {'min': 0.2222222222222222,
  'max': 0.7777777777777778,
  'mean': 0.5037037037037037,
  'stddev': 0.14833321773704286},
 'accuracy': {'min': 0.2222222222222222,
  'max': 0.7777777777777778,
  'mean': 0.5037037037037037,
  'stddev': 0.14833321773704286}}

### For S1Q06_P1 Column

In [78]:
x_data = after_preprocess_[invcot_cols]
y_data = after_preprocess_["S1Q06_P1nor"]
invcot_ap_results_s1q06p1 = make_results(n_splits=30,
                                 x_data=x_data,
                                 y_data=y_data,
                                 base_model=DecisionTreeRegressor,
                                 metrics=regression_metrics)
invcot_ap_results_s1q06p1

{'r2': {'min': -28.875000000000018,
  'max': 0.31498749999999986,
  'mean': -5.548468953455574,
  'stddev': 8.065710572158109},
 'mean_squared': {'min': 0.0012538580246913586,
  'max': 0.06190399546682099,
  'mean': 0.015446875301408177,
  'stddev': 0.014050846001885758},
 'mean_absolute': {'min': 0.013888888888888895,
  'max': 0.15416666666666667,
  'mean': 0.07759645061728397,
  'stddev': 0.03898713146114395}}

# Conclusion
Here we will show every thing in a single table.

In [79]:
from IPython.display import display
from IPython.display import HTML

In [80]:
df1 = pd.concat(
    [
        pd.DataFrame(dataset_b_results_s1q061).T.stack().to_frame().T,
        pd.DataFrame(invbool_b_results_s1q061).T.stack().to_frame().T,
        pd.DataFrame(invcot_b_results_s1q061).T.stack().to_frame().T,
    ]
)
df1.index = pd.MultiIndex.from_product([["Dataset b"], ["Full", "InvBool", "InvCot"]])
df2 = pd.concat(
    [
        pd.DataFrame(dataset_anotp_results_s1q061).T.stack().to_frame().T,
        pd.DataFrame(invbool_anotp_results_s1q061).T.stack().to_frame().T,
        pd.DataFrame(invcot_anotp_results_s1q061).T.stack().to_frame().T,
    ]
)
df2.index = pd.MultiIndex.from_product([["Dataset anotp"], ["Full", "InvBool", "InvCot"]])

df3 = pd.concat(
    [
        pd.DataFrame(dataset_ap_results_s1q061).T.stack().to_frame().T,
        pd.DataFrame(invbool_ap_results_s1q061).T.stack().to_frame().T,
        pd.DataFrame(invcot_ap_results_s1q061).T.stack().to_frame().T,
    ]
)
df3.index = pd.MultiIndex.from_product([["Dataset ap"], ["Full", "InvBool", "InvCot"]])
df_s1q0p61 = pd.concat([df1, df2, df3])
df_s1q0p61

                             f1                               precision       \
                            min       max      mean    stddev       min  max
Dataset b     Full     0.888889  1.000000  0.994336  0.022244  0.911111  1.0
              InvBool  0.000000  0.941176  0.582320  0.242177  0.000000  1.0
              InvCot   0.000000  0.941176  0.576138  0.269369  0.000000  1.0
Dataset anotp Full     0.888889  1.000000  0.994336  0.022244  0.911111  1.0
              InvBool  0.000000  0.941176  0.561864  0.247292  0.000000  1.0
              InvCot   0.200000  0.941176  0.608705  0.197261  0.592593  1.0
Dataset ap    Full     0.883951  1.000000  0.992428  0.028339  0.911111  1.0
              InvBool  0.166667  0.882828  0.464368  0.181028  0.166667  1.0
              InvCot   0.177778  0.792023  0.503059  0.165222  0.148148  1.0

                                             recall                      \
                           mean    stddev       min       max      mean
Dataset b     Full     0.997037  0.015956  0.888889  1.000000  0.992593
              InvBool  0.921693  0.250671  0.000000  0.888889  0.455556
              InvCot   0.918765  0.251717  0.000000  0.888889  0.459259
Dataset anotp Full     0.997037  0.015956  0.888889  1.000000  0.992593
              InvBool  0.952407  0.186608  0.000000  0.888889  0.437037
              InvCot   0.983642  0.074139  0.111111  0.888889  0.474074
Dataset ap    Full     0.994074  0.022173  0.888889  1.000000  0.992593
              InvBool  0.536130  0.223488  0.111111  0.888889  0.459259
              InvCot   0.542187  0.218110  0.222222  0.777778  0.503704

                                 accuracy
                         stddev       min       max      mean    stddev
Dataset b     Full     0.027716  0.888889  1.000000  0.992593  0.027716
              InvBool  0.235440  0.000000  0.888889  0.455556  0.235440
              InvCot   0.257774  0.000000  0.888889  0.459259  0.257774
Dataset anotp Full     0.027716  0.888889  1.000000  0.992593  0.027716
              InvBool  0.241622  0.000000  0.888889  0.437037  0.241622
              InvCot   0.196541  0.111111  0.888889  0.474074  0.196541
Dataset ap    Full     0.027716  0.888889  1.000000  0.992593  0.027716
              InvBool  0.194012  0.111111  0.888889  0.459259  0.194012
              InvCot   0.148333  0.222222  0.777778  0.503704  0.148333

In [81]:
df1 = pd.concat(
    [
        pd.DataFrame(dataset_b_results_s1q06p1).T.stack().to_frame().T,
        pd.DataFrame(invbool_b_results_s1q06p1).T.stack().to_frame().T,
        pd.DataFrame(invcot_b_results_s1q06p1).T.stack().to_frame().T,
    ]
)
df1.index = pd.MultiIndex.from_product([["Dataset b"], ["Full", "InvBool", "InvCot"]])
df2 = pd.concat(
    [
        pd.DataFrame(dataset_anotp_results_s1q06p1).T.stack().to_frame().T,
        pd.DataFrame(invbool_anotp_results_s1q06p1).T.stack().to_frame().T,
        pd.DataFrame(invcot_anotp_results_s1q06p1).T.stack().to_frame().T,
    ]
)
df2.index = pd.MultiIndex.from_product([["Dataset anotp"], ["Full", "InvBool", "InvCot"]])

df3 = pd.concat(
    [
        pd.DataFrame(dataset_ap_results_s1q06p1).T.stack().to_frame().T,
        pd.DataFrame(invbool_ap_results_s1q06p1).T.stack().to_frame().T,
        pd.DataFrame(invcot_ap_results_s1q06p1).T.stack().to_frame().T,
    ]
)
df3.index = pd.MultiIndex.from_product([["Dataset ap"], ["Full", "InvBool", "InvCot"]])
df_s1q0p6p1 = pd.concat([df1, df2, df3])
df_s1q0p6p1

                               r2                                  \
                              min       max       mean     stddev
Dataset b     Full     -33.385870  1.000000  -1.670061   6.994182
              InvBool  -51.728225  0.000000  -3.865392   9.635074
              InvCot  -475.505000  0.000000 -19.178234  85.261089
Dataset anotp Full     -54.125000  1.000000  -4.199885  12.698597
              InvBool -105.470000  0.000000  -7.582676  20.611538
              InvCot   -58.577320  0.051796  -5.581692  12.308974
Dataset ap    Full     -48.590179  1.000000  -2.427233   9.476755
              InvBool  -75.320000  0.007838  -7.718837  14.411395
              InvCot   -28.875000  0.314987  -5.548469   8.065711

                       mean_squared                                       \
                                min          max        mean      stddev
Dataset b     Full     0.000000e+00  1796.555556  200.510657  405.370849
              InvBool  2.777778e+01  1944.223333  594.982685  578.307601
              InvCot   2.777778e+00  2451.695556  549.522315  599.899378
Dataset anotp Full     0.000000e+00  1163.557778  267.405028  396.626782
              InvBool  3.513889e+01  2211.112222  632.103157  619.853783
              InvCot   6.111111e+01  4016.666667  703.969222  844.474375
Dataset ap    Full     2.396713e-33     0.024000    0.005255    0.007138
              InvBool  1.883801e-03     0.052520    0.018867    0.015359
              InvCot   1.253858e-03     0.061904    0.015447    0.014051

                      mean_absolute
                                min        max       mean     stddev
Dataset b     Full     0.000000e+00  27.000000   5.631296   7.745454
              InvBool  3.333333e+00  31.555556  14.016296   7.788772
              InvCot   5.555556e-01  33.222222  14.293704   8.945307
Dataset anotp Full     0.000000e+00  24.422222   6.106111   7.915637
              InvBool  3.166667e+00  31.666667  15.066111   8.850178
              InvCot   4.138889e+00  47.777778  16.210370  10.246178
Dataset ap    Full     4.317534e-17   0.079861   0.027539   0.019770
              InvBool  2.488426e-02   0.164988   0.081099   0.038682
              InvCot   1.388889e-02   0.154167   0.077596   0.038987